# Generated by Django 5.2.4 on 2025-07-21 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id_asiento', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_asiento', models.DateField()),
                ('numero_asiento', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('id_documento_origen', models.UUIDField(blank=True, null=True)),
                ('nombre_modelo_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_asiento', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('id_usuario_registro_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id_cuenta_contable', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(max_length=50, unique=True)),
                ('nombre_cuenta', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], max_length=50)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=10)),
                ('nivel', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id_detalle_asiento', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('descripcion_detalle', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.asientocontable')),
                ('id_cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas')),
            ],
        ),
    ]
