# Generated by Django 5.2.4 on 2025-07-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_sucursal_predeterminada',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresas',
            field=models.ManyToManyField(related_name='usuarios', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sucursales',
            field=models.ManyToManyField(related_name='usuarios', to='core.sucursal'),
        ),
    ]
