# Generated by Django 5.2.4 on 2025-07-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuarios_id_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_sucursal_predeterminada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_predeterminados', to='core.sucursal', verbose_name='Sucursal predeterminada'),
        ),
    ]
