# Generated by Django 5.2.4 on 2025-07-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarios_id_sucursal_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='departamento_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartamentos', to='core.departamento', verbose_name='Dirección General'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiarias', to='core.empresa', verbose_name='Empresa Matriz'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsucursales', to='core.sucursal', verbose_name='Sucursal Matriz'),
        ),
    ]
