# Generated by Django 5.2.4 on 2025-07-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_rename_activo_caja_activa_and_more'),
        ('tesoreria', '0002_operacioncambiodivisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientointernofondo',
            name='caja_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='finanzas.caja'),
        ),
        migrations.AlterField(
            model_name='movimientointernofondo',
            name='caja_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='finanzas.caja'),
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
