# Generated by Django 5.2.4 on 2025-07-21 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('inventario', '0003_stockconsignacioncliente_stockconsignacionproveedor_and_more'),
        ('manufactura', '0001_initial'),
        ('rrhh', '0002_beneficio_beneficioempleado_tipolicencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id_centro_trabajo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_centro', models.CharField(max_length=50, unique=True)),
                ('nombre_centro', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_centro', models.CharField(choices=[('MAQUINA', 'Máquina'), ('MANUAL', 'Manual'), ('ENSAMBLE', 'Ensamble'), ('CONTROL_CALIDAD', 'Control de Calidad'), ('EMPAQUE', 'Empaque')], max_length=20)),
                ('capacidad_horas_dia', models.DecimalField(decimal_places=2, default=8.0, max_digits=8)),
                ('costo_hora', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_trabajo', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Centro de Trabajo',
                'verbose_name_plural': 'Centros de Trabajo',
                'db_table': 'manufactura_centro_trabajo',
            },
        ),
        migrations.CreateModel(
            name='ListaMaterialesDetalle',
            fields=[
                ('id_detalle_lista', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('es_opcional', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_lista_materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='manufactura.listamateriales')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_lista_materiales', to='inventario.producto')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_lista_materiales', to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Detalle de Lista de Materiales',
                'verbose_name_plural': 'Detalles de Lista de Materiales',
                'db_table': 'manufactura_lista_materiales_detalle',
            },
        ),
        migrations.CreateModel(
            name='OperacionProduccion',
            fields=[
                ('id_operacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_operacion', models.CharField(max_length=50, unique=True)),
                ('nombre_operacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_estandar_minutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_produccion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Operación de Producción',
                'verbose_name_plural': 'Operaciones de Producción',
                'db_table': 'manufactura_operacion_produccion',
            },
        ),
        migrations.CreateModel(
            name='RutaProduccionDetalle',
            fields=[
                ('id_detalle_ruta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_secuencia', models.IntegerField()),
                ('tiempo_preparacion_minutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tiempo_operacion_minutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ruta', to='manufactura.centrotrabajo')),
                ('id_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ruta', to='manufactura.operacionproduccion')),
                ('id_ruta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='manufactura.rutaproduccion')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta de Producción',
                'verbose_name_plural': 'Detalles de Ruta de Producción',
                'db_table': 'manufactura_ruta_produccion_detalle',
                'ordering': ['numero_secuencia'],
            },
        ),
        migrations.CreateModel(
            name='RegistroOperacion',
            fields=[
                ('id_registro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cantidad_procesada', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_defectuosa', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EN_PROGRESO', 'En Progreso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_operacion', to='rrhh.empleado')),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_operacion', to='manufactura.ordenproduccion')),
                ('id_detalle_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='manufactura.rutaproducciondetalle')),
            ],
            options={
                'verbose_name': 'Registro de Operación',
                'verbose_name_plural': 'Registros de Operaciones',
                'db_table': 'manufactura_registro_operacion',
            },
        ),
    ]
