# Generated by Django 5.2.4 on 2025-07-19 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('simbolo', models.CharField(max_length=5)),
                ('decimales', models.IntegerField(default=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre_metodo', models.CharField(max_length=100)),
                ('tipo_metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('ELECTRONICO', 'Electrónico'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('OTRO', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id_tasa_cambio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_tasa', models.CharField(choices=[('OFICIAL_BCV', 'Oficial BCV'), ('ESPECIAL_USUARIO', 'Especial Usuario'), ('PROMEDIO_MERCADO', 'Promedio Mercado'), ('FIJA', 'Fija')], max_length=20)),
                ('valor_tasa', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fecha_tasa', models.DateField()),
                ('hora_tasa', models.TimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasa_destino', to='finanzas.moneda')),
                ('id_moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasa_origen', to='finanzas.moneda')),
                ('id_usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id_tipo_impuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre_impuesto', models.CharField(max_length=100)),
                ('codigo_impuesto', models.CharField(max_length=20, unique=True)),
                ('es_retencion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionImpuesto',
            fields=[
                ('id_configuracion_impuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('porcentaje_tasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('es_default_venta', models.BooleanField(default=False)),
                ('es_default_compra', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipoimpuesto')),
            ],
        ),
    ]
