# Generated by Django 5.2.4 on 2025-07-21 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_caja', models.CharField(max_length=100)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_finanzas', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_finanzas', to='finanzas.moneda')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_finanzas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'finanzas_caja',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaEmpresa',
            fields=[
                ('id_cuenta_bancaria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Ahorro'), ('CORRIENTE', 'Corriente'), ('CREDITO', 'Crédito')], max_length=50)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_finanzas', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_finanzas', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria Empresa',
                'verbose_name_plural': 'Cuentas Bancarias Empresa',
                'db_table': 'finanzas_cuenta_bancaria_empresa',
            },
        ),
        migrations.CreateModel(
            name='RetencionImpuesto',
            fields=[
                ('id_retencion_impuesto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_base_retencion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_retenido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_retencion', models.DateField()),
                ('numero_comprobante_retencion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('id_documento_origen', models.UUIDField(blank=True, null=True)),
                ('nombre_modelo_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_impuesto', to='core.empresa')),
                ('id_tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='finanzas.tipoimpuesto')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retención de Impuesto',
                'verbose_name_plural': 'Retenciones de Impuesto',
                'db_table': 'finanzas_retencion_impuesto',
            },
        ),
        migrations.CreateModel(
            name='TransaccionFinanciera',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_transaccion', models.DateTimeField()),
                ('tipo_transaccion', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_base_empresa', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_financieras', to='core.empresa')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.metodopago')),
                ('id_moneda_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_moneda', to='finanzas.moneda')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'db_table': 'finanzas_transaccion_financiera',
            },
        ),
    ]
