# Generated by Django 5.2.4 on 2025-07-21 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finanzas', '0002_caja_cuentabancariaempresa_retencionimpuesto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCajaBanco',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('hora_movimiento', models.TimeField()),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.caja')),
                ('id_cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.cuentabancariaempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='finanzas.moneda')),
                ('id_transaccion_financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='finanzas.transaccionfinanciera')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja/Banco',
                'verbose_name_plural': 'Movimientos de Caja/Banco',
                'db_table': 'finanzas_movimiento_caja_banco',
            },
        ),
    ]
