# Generated by Django 5.2.4 on 2025-07-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimientocajabanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='tipo_moneda',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cripto'), ('otro', 'Otro')], default='fiat', max_length=10),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo_iso',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
