# Generated by Django 5.2.4 on 2025-07-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0004_moneda_tipo_moneda_alter_moneda_codigo_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria de la moneda. Null si es genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monedas_empresa', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='es_generica',
            field=models.BooleanField(default=False, help_text='Si es True, es una moneda global del sistema, no editable por usuarios normales.'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='es_publica',
            field=models.BooleanField(default=False, help_text='Si es True, la moneda es visible para todas las empresas.'),
        ),
    ]
