# Generated by Django 5.2.4 on 2025-07-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0005_moneda_empresa_moneda_es_generica_moneda_es_publica'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonedaEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas_activas', to='core.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Moneda activa por empresa',
                'verbose_name_plural': 'Monedas activas por empresa',
                'unique_together': {('empresa', 'moneda')},
            },
        ),
    ]
