# Generated by Django 5.2.4 on 2025-07-30 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0006_monedaempresaactiva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='activo',
            new_name='activa',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='nombre_caja',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='id_moneda',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='id_sucursal',
        ),
        migrations.AddField(
            model_name='caja',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='documento_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='caja',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='finanzas.moneda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='caja',
            name='tipo_caja',
            field=models.CharField(choices=[('REGISTRADORA', 'Caja Registradora'), ('GERENCIA', 'Caja Gerente Sucursal'), ('MATRIZ', 'Caja Matriz/Principal'), ('OTRO', 'Otro')], default='REGISTRADORA', max_length=20),
        ),
    ]
