# Generated by Django 5.2.4 on 2025-07-31 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0007_rename_activo_caja_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='id_empresa',
            field=models.ForeignKey(blank=True, help_text='Para OFICIAL_BCV puede ser null y será global para todas las empresas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
