# Generated by Django 5.2.4 on 2025-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_alter_tasacambio_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo_metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('ELECTRONICO', 'Electrónico'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
