# Generated by Django 5.2.4 on 2025-07-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0009_alter_metodopago_tipo_metodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria del método. Null si es genérico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_empresa', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='es_generico',
            field=models.BooleanField(default=False, help_text='Si es True, es un método global del sistema, no editable por usuarios normales.'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='Si es True, el método es visible para todas las empresas.'),
        ),
    ]
