# Generated by Django 5.2.4 on 2025-07-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0010_remove_metodopago_id_empresa_metodopago_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagoEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_empresa_activas', to='core.empresa')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='finanzas.metodopago')),
            ],
            options={
                'verbose_name': 'Método de pago activo por empresa',
                'verbose_name_plural': 'Métodos de pago activos por empresa',
                'unique_together': {('empresa', 'metodo_pago')},
            },
        ),
    ]
