# Generated by Django 5.2.4 on 2025-07-31 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_departamento_general_and_more'),
        ('finanzas', '0011_metodopagoempresaactiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoimpuesto',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='tipoimpuesto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria del tipo de impuesto. Null si es genérico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_impuesto_empresa', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='tipoimpuesto',
            name='es_generico',
            field=models.BooleanField(default=False, help_text='Si es True, es un tipo de impuesto global del sistema, no editable por usuarios normales.'),
        ),
        migrations.AddField(
            model_name='tipoimpuesto',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='Si es True, el tipo de impuesto es visible para todas las empresas.'),
        ),
        migrations.CreateModel(
            name='TipoImpuestoEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_impuesto_empresa_activas', to='core.empresa')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='finanzas.tipoimpuesto')),
            ],
            options={
                'verbose_name': 'Tipo de impuesto activo por empresa',
                'verbose_name_plural': 'Tipos de impuesto activos por empresa',
                'unique_together': {('empresa', 'tipo_impuesto')},
            },
        ),
    ]
