# Generated by Django 5.2.4 on 2025-07-19 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaproducto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_producto', models.CharField(choices=[('PRODUCTO_FISICO', 'Producto Físico'), ('SERVICIO', 'Servicio'), ('KIT', 'Kit'), ('COMBO', 'Combo')], default='PRODUCTO_FISICO', max_length=50)),
                ('maneja_lotes', models.BooleanField(default=False)),
                ('maneja_seriales', models.BooleanField(default=False)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriaproducto')),
                ('id_configuracion_impuesto_compra_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_impuesto_compra', to='finanzas.configuracionimpuesto')),
                ('id_configuracion_impuesto_venta_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_impuesto_venta', to='finanzas.configuracionimpuesto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.moneda')),
                ('id_unidad_medida_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida')),
            ],
        ),
    ]
