# Generated by Django 5.2.4 on 2025-07-21 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_initial'),
        ('core', '0002_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id_variante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_variante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('atributos_json', models.JSONField(default=dict)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'inventario_variante_producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_movimiento', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('CONSUMO_PRODUCCION', 'Consumo Producción'), ('RECEPCION_COMPRA', 'Recepción Compra'), ('DESPACHO_VENTA', 'Despacho Venta')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario_movimiento', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('id_documento_origen', models.UUIDField(blank=True, null=True)),
                ('nombre_modelo_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='almacenes.almacen')),
                ('id_almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='core.empresa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventario_movimiento_inventario',
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id_stock_actual', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_comprometida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_en_transito', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_minima', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_maxima', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stocks Actuales',
                'db_table': 'inventario_stock_actual',
                'unique_together': {('id_producto', 'id_variante', 'id_almacen')},
            },
        ),
    ]
