# Generated by Django 5.2.4 on 2025-07-21 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0001_initial'),
        ('finanzas', '0003_movimientocajabanco'),
        ('inventario', '0002_varianteproducto_movimientoinventario_stockactual'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConsignacionCliente',
            fields=[
                ('id_stock_consignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_consignada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_vendida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_consignacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_unitario_consignacion', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='finanzas.moneda')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock en Consignación a Cliente',
                'verbose_name_plural': 'Stocks en Consignación a Clientes',
                'db_table': 'inventario_stock_consignacion_cliente',
            },
        ),
        migrations.CreateModel(
            name='StockConsignacionProveedor',
            fields=[
                ('id_stock_consignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo_unitario_consignacion', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='finanzas.moneda')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='inventario.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion', to='proveedores.proveedor')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock en Consignación de Proveedor',
                'verbose_name_plural': 'Stocks en Consignación de Proveedores',
                'db_table': 'inventario_stock_consignacion_proveedor',
            },
        ),
        migrations.CreateModel(
            name='ConversionUnidadMedida',
            fields=[
                ('id_conversion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_conversion', models.DecimalField(decimal_places=8, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to='core.empresa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to='inventario.producto')),
                ('id_unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='inventario.unidadmedida')),
                ('id_unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad de Medida',
                'verbose_name_plural': 'Conversiones de Unidades de Medida',
                'db_table': 'inventario_conversion_unidad_medida',
                'unique_together': {('id_producto', 'id_unidad_origen', 'id_unidad_destino')},
            },
        ),
    ]
