# Generated by Django 5.2.4 on 2025-07-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
    ]
