# Generated by Django 5.2.4 on 2025-07-21 17:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0002_initial'),
        ('inventario', '0003_stockconsignacioncliente_stockconsignacionproveedor_and_more'),
        ('proveedores', '0002_contactoproveedor_cuentabancariaproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id_detalle_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura_compra', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Factura de Compra',
                'db_table': 'compras_detalle_factura_compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionMercancia',
            fields=[
                ('id_detalle_recepcion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_esperada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado_mercancia', models.CharField(choices=[('CONFORME', 'Conforme'), ('DEFECTUOSO', 'Defectuoso'), ('INCOMPLETO', 'Incompleto'), ('DAÑADO', 'Dañado')], default='CONFORME', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recepcion', to='inventario.producto')),
                ('id_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.recepcionmercancia')),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
                'db_table': 'compras_detalle_recepcion_mercancia',
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id_oferta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_oferta', models.CharField(max_length=50)),
                ('fecha_oferta', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EVALUADA', 'Evaluada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='RECIBIDA', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Oferta de Proveedor',
                'verbose_name_plural': 'Ofertas de Proveedores',
                'db_table': 'compras_oferta_proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleOfertaProveedor',
            fields=[
                ('id_detalle_oferta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_oferta', to='inventario.producto')),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ofertaproveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Oferta',
                'verbose_name_plural': 'Detalles de Oferta',
                'db_table': 'compras_detalle_oferta_proveedor',
            },
        ),
        migrations.CreateModel(
            name='RequisicionCompra',
            fields=[
                ('id_requisicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_requisicion', models.CharField(max_length=50, unique=True)),
                ('fecha_requisicion', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=15)),
                ('fecha_necesidad', models.DateField()),
                ('justificacion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='core.departamento')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_compra', to='core.empresa')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisición de Compra',
                'verbose_name_plural': 'Requisiciones de Compra',
                'db_table': 'compras_requisicion_compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleRequisicionCompra',
            fields=[
                ('id_detalle_requisicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_requisicion', to='inventario.producto')),
                ('id_requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.requisicioncompra')),
            ],
            options={
                'verbose_name': 'Detalle de Requisición',
                'verbose_name_plural': 'Detalles de Requisición',
                'db_table': 'compras_detalle_requisicion_compra',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id_solicitud_cotizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_solicitud', models.CharField(max_length=50, unique=True)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('RESPONDIDA', 'Respondida'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizacion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'db_table': 'compras_solicitud_cotizacion',
            },
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='id_solicitud_cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='compras.solicitudcotizacion'),
        ),
        migrations.CreateModel(
            name='DetalleSolicitudCotizacion',
            fields=[
                ('id_detalle_solicitud', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_solicitud_cotizacion', to='inventario.producto')),
                ('id_solicitud_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.solicitudcotizacion')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Cotización',
                'verbose_name_plural': 'Detalles de Solicitud de Cotización',
                'db_table': 'compras_detalle_solicitud_cotizacion',
            },
        ),
    ]
