# Generated by Django 5.2.4 on 2025-07-21 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimientocajabanco'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id_contacto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_contacto_principal', models.BooleanField(default=False)),
                ('area_responsabilidad', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedores',
                'db_table': 'proveedores_contacto_proveedor',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaProveedor',
            fields=[
                ('id_cuenta_bancaria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Corriente'), ('AHORRO', 'Ahorro'), ('VISTA', 'Vista'), ('PLAZO_FIJO', 'Plazo Fijo')], max_length=20)),
                ('titular_cuenta', models.CharField(blank=True, max_length=200, null=True)),
                ('identificacion_titular', models.CharField(blank=True, max_length=50, null=True)),
                ('es_cuenta_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='proveedores.proveedor')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_proveedores', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria de Proveedor',
                'verbose_name_plural': 'Cuentas Bancarias de Proveedores',
                'db_table': 'proveedores_cuenta_bancaria_proveedor',
                'unique_together': {('nombre_banco', 'numero_cuenta')},
            },
        ),
    ]
