# Generated by Django 5.2.4 on 2025-07-21 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id_contacto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('apellido_contacto', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_directo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('es_contacto_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_cliente', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Cliente',
                'db_table': 'crm_contacto_cliente',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_direccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_direccion', models.CharField(choices=[('FISCAL', 'Fiscal'), ('COMERCIAL', 'Comercial'), ('ENTREGA', 'Entrega'), ('FACTURACION', 'Facturación'), ('OTRA', 'Otra')], max_length=20)),
                ('direccion_completa', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado_provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(default='Venezuela', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('es_direccion_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Dirección de Cliente',
                'verbose_name_plural': 'Direcciones de Cliente',
                'db_table': 'crm_direccion_cliente',
            },
        ),
    ]
