# Generated by Django 5.2.4 on 2025-07-19 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=100)),
                ('codigo_almacen', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
