# Generated by Django 5.2.4 on 2025-07-21 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('crm', '0002_contactocliente_direccioncliente'),
        ('finanzas', '0003_movimientocajabanco'),
        ('inventario', '0003_stockconsignacioncliente_stockconsignacionproveedor_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=50, unique=True)),
                ('fecha_cotizacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=30)),
                ('monto_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('condiciones_comerciales', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'ventas_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle_cotizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cotizacion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cotizacion', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cotizacion', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'db_table': 'ventas_detalle_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'ventas_detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id_devolucion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_devolucion', models.CharField(max_length=50, unique=True)),
                ('fecha_devolucion', models.DateField()),
                ('motivo_devolucion', models.CharField(choices=[('DEFECTO', 'Defecto'), ('GARANTIA', 'Garantía'), ('ERROR_ENTREGA', 'Error de Entrega'), ('CAMBIO_CLIENTE', 'Cambio de Cliente'), ('VENCIMIENTO', 'Vencimiento'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('PROCESADA', 'Procesada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_venta', to='core.empresa')),
                ('id_factura_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.factura')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_venta', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Venta',
                'db_table': 'ventas_devolucion_venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionVenta',
            fields=[
                ('id_detalle_devolucion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado_producto', models.CharField(choices=[('BUENO', 'Bueno'), ('DEFECTUOSO', 'Defectuoso'), ('VENCIDO', 'Vencido'), ('DAÑADO', 'Dañado')], max_length=20)),
                ('accion_inventario', models.CharField(choices=[('REINTEGRAR', 'Reintegrar a Stock'), ('CUARENTENA', 'Enviar a Cuarentena'), ('DESCARTAR', 'Descartar'), ('REPARAR', 'Enviar a Reparación')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devolucion', to='inventario.varianteproducto')),
                ('id_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucionventa')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
                'db_table': 'ventas_detalle_devolucion_venta',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoVenta',
            fields=[
                ('id_nota_credito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_nota_credito', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('DESCUENTO', 'Descuento'), ('ERROR_FACTURACION', 'Error de Facturación'), ('ANULACION', 'Anulación'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('APLICADA', 'Aplicada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_venta', to='core.empresa')),
                ('id_factura_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='ventas.factura')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_venta', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Nota de Crédito de Venta',
                'verbose_name_plural': 'Notas de Crédito de Venta',
                'db_table': 'ventas_nota_credito_venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCreditoVenta',
            fields=[
                ('id_detalle_nota_credito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_credito', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_credito', to='inventario.varianteproducto')),
                ('id_nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacreditoventa')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Nota de Crédito',
                'db_table': 'ventas_detalle_nota_credito_venta',
            },
        ),
    ]
