# Generated by Django 5.2.4 on 2025-07-21 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log_auditoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_entidad_afectada', models.UUIDField(blank=True, null=True)),
                ('nombre_entidad_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('modulo', models.CharField(max_length=50)),
                ('tipo_accion', models.CharField(max_length=50)),
                ('descripcion_accion', models.TextField(blank=True, null=True)),
                ('cambios_json', models.JSONField(blank=True, null=True)),
                ('fecha_hora_accion', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador_info', models.TextField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
